# Ce fichier peut être utilisé pour déployer une unique stack passée en var 'stack_to_deploy'
- name: Deployer single stack - ensure dir
  file:
    path: "{{ docker_root }}/{{ stack_to_deploy.name }}"
    state: directory

- name: Render compose pour single stack
  template:
    src: "{{ stack_to_deploy.compose_template }}"
    dest: "{{ docker_root }}/{{ stack_to_deploy.name }}/docker-compose.yml"
  when: stack_to_deploy.compose_template is defined

- name: Deploy single stack
  command: "{{ docker_compose_cmd }} -p {{ stack_to_deploy.name }} -f docker-compose.yml up -d"
  args:
    chdir: "{{ docker_root }}/{{ stack_to_deploy.name }}"