---
- name: Installer les paquets de base nécessaires
  ansible.builtin.apt:
    name:
      - git
      - curl
      - ca-certificates
      - unzip
      - make
      - htop
      - apt-transport-https
      - software-properties-common
      - net-tools
    state: present
    update_cache: true
