# racine des compose/configs
docker_root: "/home/{{ ansible_user }}/docker"

# racine des données persistantes
docker_data_root: "/home/{{ ansible_user }}/docker-data"


# liste des stacks à déployer (doit être fournie par le playbook ou les host_vars)
# exemple d’élément :
# - name: portainer
#   compose_template: portainer/docker-compose.yml.j2
#   env_template: portainer/.env.j2
#   data_dirs: [data]
stacks: []

# options
stack_deployer_chown_owner: "{{ ansible_user }}"
stack_deployer_chown_group: "{{ ansible_user }}"
# pour les répertoires de données, on préfère le groupe 'docker'
stack_deployer_data_group: docker
stack_deployer_data_mode: '2770'

# commande docker compose (utilise CLI docker compose)
docker_compose_cmd: docker compose

# comportement quand les stacks ne sont pas définies : scanner docker_root pour les sous-répertoires
stack_deployer_scan_if_empty: true