---
- name: Web server containers deploy
  hosts: web
  become: true
  gather_facts: true
  
  vars:
    docker_users:
      - "{{ ansible_user }}"
    stacks:
      - name: portainer
        compose_template: portainer/docker-compose.yml.j2
        data_dirs: [data]
  roles:
    - role: stack_deployer
