- name: S’assurer que la locale {{ system_locale }} existe
  community.general.locale_gen:
    name: "{{ system_locale }}"
    state: present
  tags:
    - baseline
    - locale

- name: Définir la locale système par défaut
  ansible.builtin.lineinfile:
    path: /etc/default/locale
    regexp: '^LANG='
    line: "LANG={{ system_locale }}"
  tags:
    - baseline
    - locale

- name: Définir LC_ALL
  ansible.builtin.lineinfile:
    path: /etc/default/locale
    regexp: '^LC_ALL='
    line: "LC_ALL=fr_FR.UTF-8"